version: "3.5"
services:
  deep_rl:
    image: deep_rl:latest
    environment:
      - SDL_VIDEODRIVER=x11
      # Remove this line if you don't have a cuda capable device
      - SDL_HINT_CUDA_DEVICE=0
      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
    deploy:
      resources:  
        # use the graphics card (comment out if there is no nvidia card)
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"